#theme = "onedark"
#theme = "dark_plus"
#theme = "gruvbox"
#theme = "base16_transparent"

# theme = "emacs"
# theme = "pop-dark"
# theme = "autumn"
# theme = "meliora"
# theme = "fleet_dark"
# theme = "varua"
# theme = "zenburn"
# theme = "monokai"
# theme = "serika-dark"
# theme = "catppuccin_macchiato"
# theme = "rasmus"
# theme = "kanagawa"
# theme = "hex_steel"
# theme = "gruvbox_light"
# theme = "gruvbox_dark_hard"
# theme = "everforest_dark"
# theme = "Nord"
theme = "rose_pine"

[editor]
lsp.display-inlay-hints = true
# Whether to apply completion item instantly when selected.
bufferline = "multiple"
cursorline = true
color-modes = true
line-number = "relative"
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"#"underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false


[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
G = "goto_file_end"
"C-j" = "goto_next_paragraph"
"C-k" = "goto_prev_paragraph"
"C-l" = "move_next_word_end"
"C-h" = "move_prev_word_start"
"A-q" = "search"
"H" = ":buffer-previous"
"L" = ":buffer-next"

#https://docs.helix-editor.com/keymap.html#normal-mode
[keys.normal.space]
q = ":quit"
w = ":write"
c = ":buffer-close"

[keys.insert]
"C-c" = ["normal_mode","normal_mode"] # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
"A-p" = "paste_after"  
"A-u" = "undo"


# [editor.explorer]
# column-width = 25
  



[editor.soft-wrap]
enable = true
max-wrap = 80 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it


[editor.statusline]
# left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "total-line-numbers", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


