cheatpaths:
  - name: personal                      # a name for the cheatpath
    path: ~/.local/share/cheat/personal # the path's location on the filesystem
    tags: [ personal ]                  # these tags will be applied to all sheets on the path
    readonly: false                      # if true, `cheat` will not create new cheatsheets here

  - name: community                     # a name for the cheatpath
    path: /usr/share/cheat/cheatsheets/community # the path's location on the filesystem
    tags: [ community ]                  # these tags will be applied to all sheets on the path
    readonly: true                      # if true, `cheat` will not create new cheatsheets here
